services:
  bot:
    container_name: tgbot
    build: .
  db:
    container_name: db
    image: postgres:15
    volumes:  # исправлено с "vollumes" на "volumes"
      - postgres_data:/var/lib/postgresql/data/
    environment:  # исправлено с "enviroment" на "environment"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_database"
    ports:
      - "5432:5432"  # указаны оба порта для хоста и контейнера
volumes:  # исправлено с "vollumes" на "volumes"
  postgres_data:

